In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [6]:
# Combined the latest 6-month datasets

files = [
    "data/CRMLSSold202512.csv",
    "data/CRMLSSold202601.csv",
    "data/CRMLSSold202602.csv",
    "data/CRMLSSold202603.csv",
    "data/CRMLSSold202604.csv",
    "data/CRMLSSold202605.csv",
]

df = pd.concat([pd.read_csv(file) for file in files], ignore_index=True)

print(df.shape)

/var/folders/fc/gqd35_1j453fd07q0583s4840000gn/T/ipykernel_3707/1949608247.py:12: DtypeWarning: Columns (4,74) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat([pd.read_csv(file) for file in files], ignore_index=True)

(112697, 80)

In [7]:
# Filter to Residential Single Family
df = df[
    (df["PropertyType"] == "Residential") &
    (df["PropertySubType"] == "SingleFamilyResidence")
].copy()

In [8]:
print("Rows:", len(df))
print("Columns:", len(df.columns))

df.head()

Rows: 55582
Columns: 80

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName
0,ContraCosta,ContraCosta,"Carpet,Tile,Wood",NaN,NaN,NaN,False,1998000.0,1150041639,teresa@teresahooper.com,...,NaN,False,3.0,San Ramon Valley,94596,975.0,10080.0,NaN,NaN,NaN
2,SanDiego,SanDiego,"Carpet,Wood",True,NaN,NaN,False,2214421.0,1150038683,laura@lauralothianrealestate.com,...,NaN,False,3.0,NaN,91364,NaN,34745.0,NaN,NaN,NaN
3,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,1200000.0,1150038607,trung.lam@kw.com,...,NaN,False,2.0,Other,95121,NaN,6600.0,NaN,NaN,NaN
7,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,3100000.0,1150032869,vickie@realsmartgroup.com,...,NaN,False,1.0,San Jose Unified,95124,NaN,8262.0,NaN,NaN,NaN
9,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,2900000.0,1150028403,vickie@realsmartgroup.com,...,NaN,False,2.0,Other,95128,NaN,9222.0,NaN,NaN,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55582 entries, 0 to 112693
Data columns (total 80 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   BuyerAgentAOR                 51709 non-null  object
 1   ListAgentAOR                  55566 non-null  object
 2   Flooring                      35280 non-null  object
 3   ViewYN                        50521 non-null  object
 4   WaterfrontYN                  35 non-null     object
 5   BasementYN                    1332 non-null   object
 6   PoolPrivateYN                 51107 non-null  object
 7   OriginalListPrice             55425 non-null  float64
 8   ListingKey                    55582 non-null  int64
 9   ListAgentEmail                17900 non-null  object
 10  CloseDate                     55582 non-null  object
 11  ClosePrice                    55582 non-null  float64
 12  ListAgentFirstName            55235 non-null  object
 13  ListAgentLastName             55581 non-null  object
 14  Latitude                      55327 non-null  float64
 15  Longitude                     55327 non-null  float64
 16  UnparsedAddress               55494 non-null  object
 17  PropertyType                  55582 non-null  object
 18  LivingArea                    55552 non-null  float64
 19  ListPrice                     55582 non-null  float64
 20  DaysOnMarket                  55582 non-null  int64
 21  ListOfficeName                55582 non-null  object
 22  BuyerOfficeName               54909 non-null  object
 23  CoListOfficeName              12872 non-null  object
 24  ListAgentFullName             55558 non-null  object
 25  CoListAgentFirstName          12827 non-null  object
 26  CoListAgentLastName           12874 non-null  object
 27  BuyerAgentMlsId               55478 non-null  object
 28  BuyerAgentFirstName           55340 non-null  object
 29  BuyerAgentLastName            55533 non-null  object
 30  FireplacesTotal               0 non-null      float64
 31  AssociationFeeFrequency       14365 non-null  object
 32  AboveGradeFinishedArea        0 non-null      float64
 33  ListingKeyNumeric             55582 non-null  int64
 34  MLSAreaMajor                  47396 non-null  object
 35  TaxAnnualAmount               0 non-null      float64
 36  CountyOrParish                55582 non-null  object
 37  MlsStatus                     55582 non-null  object
 38  ElementarySchool              7141 non-null   object
 39  AttachedGarageYN              48820 non-null  object
 40  ParkingTotal                  55582 non-null  float64
 41  BuilderName                   2499 non-null   object
 42  PropertySubType               55582 non-null  object
 43  LotSizeAcres                  54548 non-null  float64
 44  SubdivisionName               19865 non-null  object
 45  BuyerOfficeAOR                49777 non-null  object
 46  YearBuilt                     55548 non-null  float64
 47  StreetNumberNumeric           55479 non-null  float64
 48  ListingId                     55582 non-null  object
 49  BathroomsTotalInteger         55581 non-null  float64
 50  City                          55571 non-null  object
 51  TaxYear                       0 non-null      float64
 52  BuildingAreaTotal             3699 non-null   float64
 53  BedroomsTotal                 55582 non-null  float64
 54  ContractStatusChangeDate      55582 non-null  object
 55  ElementarySchoolDistrict      0 non-null      float64
 56  CoBuyerAgentFirstName         5272 non-null   object
 57  PurchaseContractDate          55579 non-null  object
 58  ListingContractDate           55582 non-null  object
 59  BelowGradeFinishedArea        409 non-null    float64
 60  BusinessType                  0 non-null      object
 61  StateOrProvince               55582 non-null  object
 62  CoveredSpaces                 0 non-null      float64
 63  MiddleOrJuniorSchool          7119 non-null   object
 64  FireplaceYN                   55530 non-null  object
 65  Stories                       49616 non-null  float64
 66  HighSchool                    9422 non-null   object
 67  Levels                        51317 non-null  object
 68  LotSizeDimensions             3407 non-null   object
 69  LotSizeArea                   54553 non-null  float64
 70  MainLevelBedrooms             33391 non-null  float64
 71  NewConstructionYN             51332 non-null  object
 72  GarageSpaces                  53440 non-null  float64
 73  HighSchoolDistrict            40335 non-null  object
 74  PostalCode                    55581 non-null  object
 75  AssociationFee                39251 non-null  float64
 76  LotSizeSquareFeet             54549 non-null  float64
 77  MiddleOrJuniorSchoolDistrict  0 non-null      float64
 78  OriginatingSystemName         37637 non-null  object
 79  OriginatingSystemSubName      37637 non-null  object
dtypes: float64(27), int64(3), object(50)
memory usage: 34.3+ MB

In [10]:
df.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,ElementarySchoolDistrict,BelowGradeFinishedArea,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,5.542500e+04,5.558200e+04,5.558200e+04,55327.000000,55327.000000,55552.000000,5.558200e+04,55582.000000,0.0,0.0,...,0.0,409.000000,0.0,49616.000000,5.455300e+04,33391.000000,53440.000000,39251.00000,5.454900e+04,0.0
mean,1.356305e+06,1.146908e+09,1.278791e+06,34.729230,-118.588966,2051.613918,1.273849e+06,39.413011,NaN,NaN,...,NaN,54.885086,NaN,1.350955,1.959198e+04,2.266299,2.003649,112.37750,3.419258e+05,NaN
std,5.781800e+06,1.268421e+07,2.453080e+06,1.792573,3.322635,1029.032378,1.519307e+06,55.333559,NaN,NaN,...,NaN,219.830425,NaN,0.477274,2.125446e+05,1.457906,3.491084,381.21903,1.679085e+07,NaN
min,0.000000e+00,4.217759e+08,1.750000e+00,0.000000,-124.175789,0.000000,8.000000e+03,-39.000000,NaN,NaN,...,NaN,0.000000,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.00000,0.000000e+00,NaN
25%,6.360000e+05,1.144786e+09,6.250000e+05,33.753850,-119.162776,1384.000000,6.250000e+05,7.000000,NaN,NaN,...,NaN,0.000000,NaN,1.000000,5.380000e+03,1.000000,2.000000,0.00000,5.663000e+03,NaN
50%,8.990000e+05,1.150854e+09,9.000000e+05,34.079562,-118.026571,1824.000000,8.990000e+05,17.000000,NaN,NaN,...,NaN,0.000000,NaN,1.000000,7.004000e+03,3.000000,2.000000,0.00000,7.245000e+03,NaN
75%,1.449999e+06,1.154488e+09,1.439875e+06,34.859982,-117.253017,2450.000000,1.400000e+06,50.000000,NaN,NaN,...,NaN,0.000000,NaN,2.000000,9.875000e+03,3.000000,2.000000,135.00000,1.045400e+04,NaN
max,7.250000e+08,1.176160e+09,4.720000e+08,43.784440,118.140030,23314.000000,6.500000e+07,894.000000,NaN,NaN,...,NaN,2031.000000,NaN,2.000000,3.164242e+07,44.000000,600.000000,20712.00000,1.897474e+09,NaN

In [11]:
# Check missing values
df[[
    "ClosePrice",
    "LivingArea",
    "BedroomsTotal",
    "BathroomsTotalInteger",
    "LotSizeSquareFeet"
]].isna().sum()

ClosePrice                  0
LivingArea                 30
BedroomsTotal               0
BathroomsTotalInteger       1
LotSizeSquareFeet        1033
dtype: int64